// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: fs/dir-file.proto

package fspb

import (
	typepb "estore/protoc/typepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreationTime   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`
	LastAccessTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_access_time,json=lastAccessTime,proto3" json:"last_access_time,omitempty"`
	LastWriteTime  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_write_time,json=lastWriteTime,proto3" json:"last_write_time,omitempty"`
	Dirs           []*Dir                 `protobuf:"bytes,5,rep,name=dirs,proto3" json:"dirs,omitempty"`
	Files          []*File                `protobuf:"bytes,6,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *Dir) Reset() {
	*x = Dir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fs_dir_file_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dir) ProtoMessage() {}

func (x *Dir) ProtoReflect() protoreflect.Message {
	mi := &file_fs_dir_file_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dir.ProtoReflect.Descriptor instead.
func (*Dir) Descriptor() ([]byte, []int) {
	return file_fs_dir_file_proto_rawDescGZIP(), []int{0}
}

func (x *Dir) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dir) GetCreationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTime
	}
	return nil
}

func (x *Dir) GetLastAccessTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAccessTime
	}
	return nil
}

func (x *Dir) GetLastWriteTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastWriteTime
	}
	return nil
}

func (x *Dir) GetDirs() []*Dir {
	if x != nil {
		return x.Dirs
	}
	return nil
}

func (x *Dir) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Dataurl        string                 `protobuf:"bytes,3,opt,name=dataurl,proto3" json:"dataurl,omitempty"`
	MediaType      string                 `protobuf:"bytes,4,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Size           int32                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	CreationTime   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`         // 最後更新時間
	LastAccessTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_access_time,json=lastAccessTime,proto3" json:"last_access_time,omitempty"` // 最後更新時間
	LastWriteTime  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_write_time,json=lastWriteTime,proto3" json:"last_write_time,omitempty"`    // 最後更新時間
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fs_dir_file_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_fs_dir_file_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_fs_dir_file_proto_rawDescGZIP(), []int{1}
}

func (x *File) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetDataurl() string {
	if x != nil {
		return x.Dataurl
	}
	return ""
}

func (x *File) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *File) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *File) GetCreationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTime
	}
	return nil
}

func (x *File) GetLastAccessTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAccessTime
	}
	return nil
}

func (x *File) GetLastWriteTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastWriteTime
	}
	return nil
}

type CreateOrUpdateDirFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Dir `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateOrUpdateDirFileRequest) Reset() {
	*x = CreateOrUpdateDirFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fs_dir_file_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrUpdateDirFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateDirFileRequest) ProtoMessage() {}

func (x *CreateOrUpdateDirFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fs_dir_file_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateDirFileRequest.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateDirFileRequest) Descriptor() ([]byte, []int) {
	return file_fs_dir_file_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrUpdateDirFileRequest) GetData() []*Dir {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateOrUpdateDirFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *typepb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *CreateOrUpdateDirFileResponse) Reset() {
	*x = CreateOrUpdateDirFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fs_dir_file_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrUpdateDirFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateDirFileResponse) ProtoMessage() {}

func (x *CreateOrUpdateDirFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fs_dir_file_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateDirFileResponse.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateDirFileResponse) Descriptor() ([]byte, []int) {
	return file_fs_dir_file_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrUpdateDirFileResponse) GetResponse() *typepb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type DeleteDirFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Dir `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *DeleteDirFileRequest) Reset() {
	*x = DeleteDirFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fs_dir_file_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDirFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDirFileRequest) ProtoMessage() {}

func (x *DeleteDirFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fs_dir_file_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDirFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteDirFileRequest) Descriptor() ([]byte, []int) {
	return file_fs_dir_file_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteDirFileRequest) GetData() []*Dir {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteDirFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *typepb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *DeleteDirFileResponse) Reset() {
	*x = DeleteDirFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fs_dir_file_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDirFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDirFileResponse) ProtoMessage() {}

func (x *DeleteDirFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fs_dir_file_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDirFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteDirFileResponse) Descriptor() ([]byte, []int) {
	return file_fs_dir_file_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDirFileResponse) GetResponse() *typepb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type FindDirFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *typepb.Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	RootDir *Dir            `protobuf:"bytes,2,opt,name=root_dir,json=rootDir,proto3" json:"root_dir,omitempty"`
}

func (x *FindDirFileRequest) Reset() {
	*x = FindDirFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fs_dir_file_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindDirFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindDirFileRequest) ProtoMessage() {}

func (x *FindDirFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fs_dir_file_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindDirFileRequest.ProtoReflect.Descriptor instead.
func (*FindDirFileRequest) Descriptor() ([]byte, []int) {
	return file_fs_dir_file_proto_rawDescGZIP(), []int{6}
}

func (x *FindDirFileRequest) GetRequest() *typepb.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *FindDirFileRequest) GetRootDir() *Dir {
	if x != nil {
		return x.RootDir
	}
	return nil
}

type FindDirFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *typepb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	RootDir  *Dir             `protobuf:"bytes,2,opt,name=root_dir,json=rootDir,proto3" json:"root_dir,omitempty"`
}

func (x *FindDirFileResponse) Reset() {
	*x = FindDirFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fs_dir_file_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindDirFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindDirFileResponse) ProtoMessage() {}

func (x *FindDirFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fs_dir_file_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindDirFileResponse.ProtoReflect.Descriptor instead.
func (*FindDirFileResponse) Descriptor() ([]byte, []int) {
	return file_fs_dir_file_proto_rawDescGZIP(), []int{7}
}

func (x *FindDirFileResponse) GetResponse() *typepb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *FindDirFileResponse) GetRootDir() *Dir {
	if x != nil {
		return x.RootDir
	}
	return nil
}

var File_fs_dir_file_proto protoreflect.FileDescriptor

var file_fs_dir_file_proto_rawDesc = []byte{
	0x0a, 0x11, 0x66, 0x73, 0x2f, 0x64, 0x69, 0x72, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x66, 0x73, 0x1a, 0x13, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa1, 0x02,
	0x0a, 0x03, 0x44, 0x69, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3f, 0x0a, 0x0d, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x44, 0x0a, 0x10, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x42, 0x0a, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x04, 0x64, 0x69, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x07, 0x2e, 0x66, 0x73, 0x2e, 0x44, 0x69, 0x72, 0x52, 0x04, 0x64, 0x69, 0x72,
	0x73, 0x12, 0x1e, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x66, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x22, 0xc2, 0x02, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x64, 0x61, 0x74, 0x61, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x64, 0x61, 0x74, 0x61, 0x75, 0x72, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x64, 0x69,
	0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65,
	0x64, 0x69, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x3f, 0x0a, 0x0d, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x44, 0x0a, 0x10,
	0x6c, 0x61, 0x73, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x42, 0x0a, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x65,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x3b, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x66, 0x73, 0x2e, 0x44, 0x69, 0x72, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x4c, 0x0a, 0x1d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x33, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x72, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x66, 0x73, 0x2e, 0x44, 0x69, 0x72,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x44, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x44, 0x69, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2b, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x62, 0x0a, 0x12,
	0x46, 0x69, 0x6e, 0x64, 0x44, 0x69, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x08,
	0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07,
	0x2e, 0x66, 0x73, 0x2e, 0x44, 0x69, 0x72, 0x52, 0x07, 0x72, 0x6f, 0x6f, 0x74, 0x44, 0x69, 0x72,
	0x22, 0x66, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x64, 0x44, 0x69, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x64, 0x69, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x66, 0x73, 0x2e, 0x44, 0x69, 0x72, 0x52,
	0x07, 0x72, 0x6f, 0x6f, 0x74, 0x44, 0x69, 0x72, 0x42, 0x14, 0x5a, 0x12, 0x65, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x66, 0x73, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fs_dir_file_proto_rawDescOnce sync.Once
	file_fs_dir_file_proto_rawDescData = file_fs_dir_file_proto_rawDesc
)

func file_fs_dir_file_proto_rawDescGZIP() []byte {
	file_fs_dir_file_proto_rawDescOnce.Do(func() {
		file_fs_dir_file_proto_rawDescData = protoimpl.X.CompressGZIP(file_fs_dir_file_proto_rawDescData)
	})
	return file_fs_dir_file_proto_rawDescData
}

var file_fs_dir_file_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_fs_dir_file_proto_goTypes = []interface{}{
	(*Dir)(nil),                           // 0: fs.Dir
	(*File)(nil),                          // 1: fs.File
	(*CreateOrUpdateDirFileRequest)(nil),  // 2: fs.CreateOrUpdateDirFileRequest
	(*CreateOrUpdateDirFileResponse)(nil), // 3: fs.CreateOrUpdateDirFileResponse
	(*DeleteDirFileRequest)(nil),          // 4: fs.DeleteDirFileRequest
	(*DeleteDirFileResponse)(nil),         // 5: fs.DeleteDirFileResponse
	(*FindDirFileRequest)(nil),            // 6: fs.FindDirFileRequest
	(*FindDirFileResponse)(nil),           // 7: fs.FindDirFileResponse
	(*timestamppb.Timestamp)(nil),         // 8: google.protobuf.Timestamp
	(*typepb.Response)(nil),               // 9: types.Response
	(*typepb.Request)(nil),                // 10: types.Request
}
var file_fs_dir_file_proto_depIdxs = []int32{
	8,  // 0: fs.Dir.creation_time:type_name -> google.protobuf.Timestamp
	8,  // 1: fs.Dir.last_access_time:type_name -> google.protobuf.Timestamp
	8,  // 2: fs.Dir.last_write_time:type_name -> google.protobuf.Timestamp
	0,  // 3: fs.Dir.dirs:type_name -> fs.Dir
	1,  // 4: fs.Dir.files:type_name -> fs.File
	8,  // 5: fs.File.creation_time:type_name -> google.protobuf.Timestamp
	8,  // 6: fs.File.last_access_time:type_name -> google.protobuf.Timestamp
	8,  // 7: fs.File.last_write_time:type_name -> google.protobuf.Timestamp
	0,  // 8: fs.CreateOrUpdateDirFileRequest.data:type_name -> fs.Dir
	9,  // 9: fs.CreateOrUpdateDirFileResponse.response:type_name -> types.Response
	0,  // 10: fs.DeleteDirFileRequest.data:type_name -> fs.Dir
	9,  // 11: fs.DeleteDirFileResponse.response:type_name -> types.Response
	10, // 12: fs.FindDirFileRequest.request:type_name -> types.Request
	0,  // 13: fs.FindDirFileRequest.root_dir:type_name -> fs.Dir
	9,  // 14: fs.FindDirFileResponse.response:type_name -> types.Response
	0,  // 15: fs.FindDirFileResponse.root_dir:type_name -> fs.Dir
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_fs_dir_file_proto_init() }
func file_fs_dir_file_proto_init() {
	if File_fs_dir_file_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fs_dir_file_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fs_dir_file_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fs_dir_file_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrUpdateDirFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fs_dir_file_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrUpdateDirFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fs_dir_file_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDirFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fs_dir_file_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDirFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fs_dir_file_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindDirFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fs_dir_file_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindDirFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fs_dir_file_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fs_dir_file_proto_goTypes,
		DependencyIndexes: file_fs_dir_file_proto_depIdxs,
		MessageInfos:      file_fs_dir_file_proto_msgTypes,
	}.Build()
	File_fs_dir_file_proto = out.File
	file_fs_dir_file_proto_rawDesc = nil
	file_fs_dir_file_proto_goTypes = nil
	file_fs_dir_file_proto_depIdxs = nil
}
