// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: store/commodity-spec-rule.proto

package storepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rule int32

const (
	Rule_DEFAULT Rule = 0
	Rule_ALLOW   Rule = 1
	Rule_DENY    Rule = 2
)

// Enum value maps for Rule.
var (
	Rule_name = map[int32]string{
		0: "DEFAULT",
		1: "ALLOW",
		2: "DENY",
	}
	Rule_value = map[string]int32{
		"DEFAULT": 0,
		"ALLOW":   1,
		"DENY":    2,
	}
)

func (x Rule) Enum() *Rule {
	p := new(Rule)
	*p = x
	return p
}

func (x Rule) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Rule) Descriptor() protoreflect.EnumDescriptor {
	return file_store_commodity_spec_rule_proto_enumTypes[0].Descriptor()
}

func (Rule) Type() protoreflect.EnumType {
	return &file_store_commodity_spec_rule_proto_enumTypes[0]
}

func (x Rule) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Rule.Descriptor instead.
func (Rule) EnumDescriptor() ([]byte, []int) {
	return file_store_commodity_spec_rule_proto_rawDescGZIP(), []int{0}
}

// 商店可視商品規格
// 沒有設定代表預設可視
// 優先順序 deny > allow > default
type CommoditySpecRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                      // 規則編號
	StoreId     string `protobuf:"bytes,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`             // 商店編號
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                  // 規則名稱
	CommodityId string `protobuf:"bytes,4,opt,name=commodity_id,json=commodityId,proto3" json:"commodity_id,omitempty"` // 商品編號
	Sku         string `protobuf:"bytes,5,opt,name=sku,proto3" json:"sku,omitempty"`                                    // 規格編號
	Rule        Rule   `protobuf:"varint,6,opt,name=rule,proto3,enum=store.Rule" json:"rule,omitempty"`                 // 規則
}

func (x *CommoditySpecRule) Reset() {
	*x = CommoditySpecRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_store_commodity_spec_rule_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommoditySpecRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommoditySpecRule) ProtoMessage() {}

func (x *CommoditySpecRule) ProtoReflect() protoreflect.Message {
	mi := &file_store_commodity_spec_rule_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommoditySpecRule.ProtoReflect.Descriptor instead.
func (*CommoditySpecRule) Descriptor() ([]byte, []int) {
	return file_store_commodity_spec_rule_proto_rawDescGZIP(), []int{0}
}

func (x *CommoditySpecRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommoditySpecRule) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *CommoditySpecRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommoditySpecRule) GetCommodityId() string {
	if x != nil {
		return x.CommodityId
	}
	return ""
}

func (x *CommoditySpecRule) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CommoditySpecRule) GetRule() Rule {
	if x != nil {
		return x.Rule
	}
	return Rule_DEFAULT
}

var File_store_commodity_spec_rule_proto protoreflect.FileDescriptor

var file_store_commodity_spec_rule_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74,
	0x79, 0x2d, 0x73, 0x70, 0x65, 0x63, 0x2d, 0x72, 0x75, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x22, 0xa8, 0x01, 0x0a, 0x11, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x64, 0x69, 0x74, 0x79, 0x53, 0x70, 0x65, 0x63, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74, 0x79, 0x49, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x6b, 0x75, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73,
	0x6b, 0x75, 0x12, 0x1f, 0x0a, 0x04, 0x72, 0x75, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0b, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x04, 0x72,
	0x75, 0x6c, 0x65, 0x2a, 0x28, 0x0a, 0x04, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x44,
	0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x4c, 0x4c, 0x4f,
	0x57, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x45, 0x4e, 0x59, 0x10, 0x02, 0x42, 0x17, 0x5a,
	0x15, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_store_commodity_spec_rule_proto_rawDescOnce sync.Once
	file_store_commodity_spec_rule_proto_rawDescData = file_store_commodity_spec_rule_proto_rawDesc
)

func file_store_commodity_spec_rule_proto_rawDescGZIP() []byte {
	file_store_commodity_spec_rule_proto_rawDescOnce.Do(func() {
		file_store_commodity_spec_rule_proto_rawDescData = protoimpl.X.CompressGZIP(file_store_commodity_spec_rule_proto_rawDescData)
	})
	return file_store_commodity_spec_rule_proto_rawDescData
}

var file_store_commodity_spec_rule_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_store_commodity_spec_rule_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_store_commodity_spec_rule_proto_goTypes = []interface{}{
	(Rule)(0),                 // 0: store.Rule
	(*CommoditySpecRule)(nil), // 1: store.CommoditySpecRule
}
var file_store_commodity_spec_rule_proto_depIdxs = []int32{
	0, // 0: store.CommoditySpecRule.rule:type_name -> store.Rule
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_store_commodity_spec_rule_proto_init() }
func file_store_commodity_spec_rule_proto_init() {
	if File_store_commodity_spec_rule_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_store_commodity_spec_rule_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommoditySpecRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_store_commodity_spec_rule_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_store_commodity_spec_rule_proto_goTypes,
		DependencyIndexes: file_store_commodity_spec_rule_proto_depIdxs,
		EnumInfos:         file_store_commodity_spec_rule_proto_enumTypes,
		MessageInfos:      file_store_commodity_spec_rule_proto_msgTypes,
	}.Build()
	File_store_commodity_spec_rule_proto = out.File
	file_store_commodity_spec_rule_proto_rawDesc = nil
	file_store_commodity_spec_rule_proto_goTypes = nil
	file_store_commodity_spec_rule_proto_depIdxs = nil
}
