// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: store/state.proto

package storepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_None    State = 0 //
	State_Prepare State = 1 // 準備中
	State_Ready   State = 2 // 營業中
	State_Hidden  State = 3 // 維護中
	State_Removed State = 5 // 永久關閉
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "None",
		1: "Prepare",
		2: "Ready",
		3: "Hidden",
		5: "Removed",
	}
	State_value = map[string]int32{
		"None":    0,
		"Prepare": 1,
		"Ready":   2,
		"Hidden":  3,
		"Removed": 5,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_store_state_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_store_state_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_store_state_proto_rawDescGZIP(), []int{0}
}

var File_store_state_proto protoreflect.FileDescriptor

var file_store_state_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2a, 0x42, 0x0a, 0x05, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x65,
	0x61, 0x64, 0x79, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x10,
	0x03, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x10, 0x05, 0x42, 0x17,
	0x5a, 0x15, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_store_state_proto_rawDescOnce sync.Once
	file_store_state_proto_rawDescData = file_store_state_proto_rawDesc
)

func file_store_state_proto_rawDescGZIP() []byte {
	file_store_state_proto_rawDescOnce.Do(func() {
		file_store_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_store_state_proto_rawDescData)
	})
	return file_store_state_proto_rawDescData
}

var file_store_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_store_state_proto_goTypes = []interface{}{
	(State)(0), // 0: store.State
}
var file_store_state_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_store_state_proto_init() }
func file_store_state_proto_init() {
	if File_store_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_store_state_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_store_state_proto_goTypes,
		DependencyIndexes: file_store_state_proto_depIdxs,
		EnumInfos:         file_store_state_proto_enumTypes,
	}.Build()
	File_store_state_proto = out.File
	file_store_state_proto_rawDesc = nil
	file_store_state_proto_goTypes = nil
	file_store_state_proto_depIdxs = nil
}
