// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: store/type.proto

package storepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_NoType   Type = 0 //
	Type_One      Type = 1 // 一頁網店
	Type_Standard Type = 2 // 標準網店
	Type_Flash    Type = 3 // 快閃網店
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "NoType",
		1: "One",
		2: "Standard",
		3: "Flash",
	}
	Type_value = map[string]int32{
		"NoType":   0,
		"One":      1,
		"Standard": 2,
		"Flash":    3,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_store_type_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_store_type_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_store_type_proto_rawDescGZIP(), []int{0}
}

var File_store_type_proto protoreflect.FileDescriptor

var file_store_type_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2a, 0x34, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x4f, 0x6e, 0x65, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61,
	0x72, 0x64, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x10, 0x03, 0x42,
	0x17, 0x5a, 0x15, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_store_type_proto_rawDescOnce sync.Once
	file_store_type_proto_rawDescData = file_store_type_proto_rawDesc
)

func file_store_type_proto_rawDescGZIP() []byte {
	file_store_type_proto_rawDescOnce.Do(func() {
		file_store_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_store_type_proto_rawDescData)
	})
	return file_store_type_proto_rawDescData
}

var file_store_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_store_type_proto_goTypes = []interface{}{
	(Type)(0), // 0: store.Type
}
var file_store_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_store_type_proto_init() }
func file_store_type_proto_init() {
	if File_store_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_store_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_store_type_proto_goTypes,
		DependencyIndexes: file_store_type_proto_depIdxs,
		EnumInfos:         file_store_type_proto_enumTypes,
	}.Build()
	File_store_type_proto = out.File
	file_store_type_proto_rawDesc = nil
	file_store_type_proto_goTypes = nil
	file_store_type_proto_depIdxs = nil
}
