// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: types/currency.proto

package typepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency int32

const (
	Currency_Point Currency = 0
	Currency_TWD   Currency = 1
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0: "Point",
		1: "TWD",
	}
	Currency_value = map[string]int32{
		"Point": 0,
		"TWD":   1,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_types_currency_proto_enumTypes[0].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_types_currency_proto_enumTypes[0]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_types_currency_proto_rawDescGZIP(), []int{0}
}

var File_types_currency_proto protoreflect.FileDescriptor

var file_types_currency_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2a, 0x1e, 0x0a,
	0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x57, 0x44, 0x10, 0x01, 0x42, 0x16, 0x5a,
	0x14, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_types_currency_proto_rawDescOnce sync.Once
	file_types_currency_proto_rawDescData = file_types_currency_proto_rawDesc
)

func file_types_currency_proto_rawDescGZIP() []byte {
	file_types_currency_proto_rawDescOnce.Do(func() {
		file_types_currency_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_currency_proto_rawDescData)
	})
	return file_types_currency_proto_rawDescData
}

var file_types_currency_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_types_currency_proto_goTypes = []interface{}{
	(Currency)(0), // 0: types.Currency
}
var file_types_currency_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_types_currency_proto_init() }
func file_types_currency_proto_init() {
	if File_types_currency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_currency_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_currency_proto_goTypes,
		DependencyIndexes: file_types_currency_proto_depIdxs,
		EnumInfos:         file_types_currency_proto_enumTypes,
	}.Build()
	File_types_currency_proto = out.File
	file_types_currency_proto_rawDesc = nil
	file_types_currency_proto_goTypes = nil
	file_types_currency_proto_depIdxs = nil
}
