// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: stock/commodity.proto

package stockpb

import (
	fspb "estore/protoc/fspb"
	typepb "estore/protoc/typepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 商品
type Commodity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                               // 商品ID(系統產生UUID)
	ProductId string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`                                                                // 產品ID(客戶自訂預設同ID)
	State     State                  `protobuf:"varint,3,opt,name=state,proto3,enum=stock.State" json:"state,omitempty"`                                                                       // 狀態
	Cost      float64                `protobuf:"fixed64,4,opt,name=cost,proto3" json:"cost,omitempty"`                                                                                         // 成本
	Label     map[string]string      `protobuf:"bytes,5,rep,name=label,proto3" json:"label,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 標籤
	PhotoDir  *fspb.Dir              `protobuf:"bytes,6,opt,name=photo_dir,json=photoDir,proto3" json:"photo_dir,omitempty"`                                                                   // 圖片目錄
	Spec      []*Spec                `protobuf:"bytes,7,rep,name=spec,proto3" json:"spec,omitempty"`                                                                                           // 規格
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                                                // 建立時間
}

func (x *Commodity) Reset() {
	*x = Commodity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_commodity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Commodity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commodity) ProtoMessage() {}

func (x *Commodity) ProtoReflect() protoreflect.Message {
	mi := &file_stock_commodity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commodity.ProtoReflect.Descriptor instead.
func (*Commodity) Descriptor() ([]byte, []int) {
	return file_stock_commodity_proto_rawDescGZIP(), []int{0}
}

func (x *Commodity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Commodity) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Commodity) GetState() State {
	if x != nil {
		return x.State
	}
	return State_None
}

func (x *Commodity) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *Commodity) GetLabel() map[string]string {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *Commodity) GetPhotoDir() *fspb.Dir {
	if x != nil {
		return x.PhotoDir
	}
	return nil
}

func (x *Commodity) GetSpec() []*Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Commodity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateCommodityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Commodity `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateCommodityRequest) Reset() {
	*x = CreateCommodityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_commodity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCommodityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommodityRequest) ProtoMessage() {}

func (x *CreateCommodityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_commodity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommodityRequest.ProtoReflect.Descriptor instead.
func (*CreateCommodityRequest) Descriptor() ([]byte, []int) {
	return file_stock_commodity_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCommodityRequest) GetData() []*Commodity {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateCommodityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *typepb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *CreateCommodityResponse) Reset() {
	*x = CreateCommodityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_commodity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCommodityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommodityResponse) ProtoMessage() {}

func (x *CreateCommodityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_commodity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommodityResponse.ProtoReflect.Descriptor instead.
func (*CreateCommodityResponse) Descriptor() ([]byte, []int) {
	return file_stock_commodity_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCommodityResponse) GetResponse() *typepb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type UpdateCommodityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Commodity `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateCommodityRequest) Reset() {
	*x = UpdateCommodityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_commodity_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCommodityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommodityRequest) ProtoMessage() {}

func (x *UpdateCommodityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_commodity_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommodityRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommodityRequest) Descriptor() ([]byte, []int) {
	return file_stock_commodity_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCommodityRequest) GetData() []*Commodity {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateCommodityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *typepb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *UpdateCommodityResponse) Reset() {
	*x = UpdateCommodityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_commodity_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCommodityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommodityResponse) ProtoMessage() {}

func (x *UpdateCommodityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_commodity_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommodityResponse.ProtoReflect.Descriptor instead.
func (*UpdateCommodityResponse) Descriptor() ([]byte, []int) {
	return file_stock_commodity_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCommodityResponse) GetResponse() *typepb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type FindCommodityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request   *typepb.Request    `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Id        []string           `protobuf:"bytes,2,rep,name=id,proto3" json:"id,omitempty"`
	ProductId []string           `protobuf:"bytes,3,rep,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	State     []State            `protobuf:"varint,4,rep,packed,name=state,proto3,enum=stock.State" json:"state,omitempty"`
	Label     []string           `protobuf:"bytes,5,rep,name=label,proto3" json:"label,omitempty"`
	CreatedAt *typepb.Datepicker `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *FindCommodityRequest) Reset() {
	*x = FindCommodityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_commodity_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindCommodityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCommodityRequest) ProtoMessage() {}

func (x *FindCommodityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_commodity_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCommodityRequest.ProtoReflect.Descriptor instead.
func (*FindCommodityRequest) Descriptor() ([]byte, []int) {
	return file_stock_commodity_proto_rawDescGZIP(), []int{5}
}

func (x *FindCommodityRequest) GetRequest() *typepb.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *FindCommodityRequest) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *FindCommodityRequest) GetProductId() []string {
	if x != nil {
		return x.ProductId
	}
	return nil
}

func (x *FindCommodityRequest) GetState() []State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *FindCommodityRequest) GetLabel() []string {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *FindCommodityRequest) GetCreatedAt() *typepb.Datepicker {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type FindCommodityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *typepb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Data     []*Commodity     `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *FindCommodityResponse) Reset() {
	*x = FindCommodityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_commodity_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindCommodityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCommodityResponse) ProtoMessage() {}

func (x *FindCommodityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_commodity_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCommodityResponse.ProtoReflect.Descriptor instead.
func (*FindCommodityResponse) Descriptor() ([]byte, []int) {
	return file_stock_commodity_proto_rawDescGZIP(), []int{6}
}

func (x *FindCommodityResponse) GetResponse() *typepb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *FindCommodityResponse) GetData() []*Commodity {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_stock_commodity_proto protoreflect.FileDescriptor

var file_stock_commodity_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x1a, 0x11,
	0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x10, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x66, 0x73, 0x2f, 0x64, 0x69, 0x72, 0x2d, 0x66, 0x69, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe1, 0x02, 0x0a,
	0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x63, 0x6f, 0x73,
	0x74, 0x12, 0x31, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69,
	0x74, 0x79, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x12, 0x24, 0x0a, 0x09, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x5f, 0x64, 0x69,
	0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x66, 0x73, 0x2e, 0x44, 0x69, 0x72,
	0x52, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x44, 0x69, 0x72, 0x12, 0x1f, 0x0a, 0x04, 0x73, 0x70,
	0x65, 0x63, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x2e, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x39, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x1a, 0x38, 0x0a, 0x0a, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x3e, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x64,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x46, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x64,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3e, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69,
	0x74, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x46, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0xdb, 0x01, 0x0a, 0x14, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x49, 0x64, 0x12, 0x22, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0e, 0x32, 0x0c, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x30, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x70, 0x69, 0x63,
	0x6b, 0x65, 0x72, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x6a,
	0x0a, 0x15, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x64, 0x69, 0x74, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x17, 0x5a, 0x15, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x73, 0x74, 0x6f, 0x63,
	0x6b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stock_commodity_proto_rawDescOnce sync.Once
	file_stock_commodity_proto_rawDescData = file_stock_commodity_proto_rawDesc
)

func file_stock_commodity_proto_rawDescGZIP() []byte {
	file_stock_commodity_proto_rawDescOnce.Do(func() {
		file_stock_commodity_proto_rawDescData = protoimpl.X.CompressGZIP(file_stock_commodity_proto_rawDescData)
	})
	return file_stock_commodity_proto_rawDescData
}

var file_stock_commodity_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_stock_commodity_proto_goTypes = []interface{}{
	(*Commodity)(nil),               // 0: stock.Commodity
	(*CreateCommodityRequest)(nil),  // 1: stock.CreateCommodityRequest
	(*CreateCommodityResponse)(nil), // 2: stock.CreateCommodityResponse
	(*UpdateCommodityRequest)(nil),  // 3: stock.UpdateCommodityRequest
	(*UpdateCommodityResponse)(nil), // 4: stock.UpdateCommodityResponse
	(*FindCommodityRequest)(nil),    // 5: stock.FindCommodityRequest
	(*FindCommodityResponse)(nil),   // 6: stock.FindCommodityResponse
	nil,                             // 7: stock.Commodity.LabelEntry
	(State)(0),                      // 8: stock.State
	(*fspb.Dir)(nil),                // 9: fs.Dir
	(*Spec)(nil),                    // 10: stock.Spec
	(*timestamppb.Timestamp)(nil),   // 11: google.protobuf.Timestamp
	(*typepb.Response)(nil),         // 12: types.Response
	(*typepb.Request)(nil),          // 13: types.Request
	(*typepb.Datepicker)(nil),       // 14: types.Datepicker
}
var file_stock_commodity_proto_depIdxs = []int32{
	8,  // 0: stock.Commodity.state:type_name -> stock.State
	7,  // 1: stock.Commodity.label:type_name -> stock.Commodity.LabelEntry
	9,  // 2: stock.Commodity.photo_dir:type_name -> fs.Dir
	10, // 3: stock.Commodity.spec:type_name -> stock.Spec
	11, // 4: stock.Commodity.created_at:type_name -> google.protobuf.Timestamp
	0,  // 5: stock.CreateCommodityRequest.data:type_name -> stock.Commodity
	12, // 6: stock.CreateCommodityResponse.response:type_name -> types.Response
	0,  // 7: stock.UpdateCommodityRequest.data:type_name -> stock.Commodity
	12, // 8: stock.UpdateCommodityResponse.response:type_name -> types.Response
	13, // 9: stock.FindCommodityRequest.request:type_name -> types.Request
	8,  // 10: stock.FindCommodityRequest.state:type_name -> stock.State
	14, // 11: stock.FindCommodityRequest.created_at:type_name -> types.Datepicker
	12, // 12: stock.FindCommodityResponse.response:type_name -> types.Response
	0,  // 13: stock.FindCommodityResponse.data:type_name -> stock.Commodity
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_stock_commodity_proto_init() }
func file_stock_commodity_proto_init() {
	if File_stock_commodity_proto != nil {
		return
	}
	file_stock_state_proto_init()
	file_stock_spec_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_stock_commodity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Commodity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_commodity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCommodityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_commodity_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCommodityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_commodity_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCommodityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_commodity_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCommodityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_commodity_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindCommodityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_commodity_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindCommodityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stock_commodity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stock_commodity_proto_goTypes,
		DependencyIndexes: file_stock_commodity_proto_depIdxs,
		MessageInfos:      file_stock_commodity_proto_msgTypes,
	}.Build()
	File_stock_commodity_proto = out.File
	file_stock_commodity_proto_rawDesc = nil
	file_stock_commodity_proto_goTypes = nil
	file_stock_commodity_proto_depIdxs = nil
}
