// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: stock/spec.proto

package stockpb

import (
	fspb "estore/protoc/fspb"
	typepb "estore/protoc/typepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 商品規格
type Spec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sku         string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`                                                                                             // 規格編號
	CommodityId string                 `protobuf:"bytes,2,opt,name=commodity_id,json=commodityId,proto3" json:"commodity_id,omitempty"`                                                          // 商品編號
	Volume      int32                  `protobuf:"varint,3,opt,name=volume,proto3" json:"volume,omitempty"`                                                                                      // 體積
	Weight      int32                  `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`                                                                                      // 重量
	Label       map[string]string      `protobuf:"bytes,5,rep,name=label,proto3" json:"label,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 標籤
	PhotoDir    *fspb.Dir              `protobuf:"bytes,6,opt,name=photo_dir,json=photoDir,proto3" json:"photo_dir,omitempty"`                                                                   // 規格圖片
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Spec) Reset() {
	*x = Spec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_spec_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_stock_spec_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_stock_spec_proto_rawDescGZIP(), []int{0}
}

func (x *Spec) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Spec) GetCommodityId() string {
	if x != nil {
		return x.CommodityId
	}
	return ""
}

func (x *Spec) GetVolume() int32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Spec) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Spec) GetLabel() map[string]string {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *Spec) GetPhotoDir() *fspb.Dir {
	if x != nil {
		return x.PhotoDir
	}
	return nil
}

func (x *Spec) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateSpecRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Spec `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateSpecRequest) Reset() {
	*x = CreateSpecRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_spec_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSpecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpecRequest) ProtoMessage() {}

func (x *CreateSpecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_spec_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpecRequest.ProtoReflect.Descriptor instead.
func (*CreateSpecRequest) Descriptor() ([]byte, []int) {
	return file_stock_spec_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSpecRequest) GetData() []*Spec {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateSpecResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *typepb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *CreateSpecResponse) Reset() {
	*x = CreateSpecResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_spec_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSpecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpecResponse) ProtoMessage() {}

func (x *CreateSpecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_spec_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpecResponse.ProtoReflect.Descriptor instead.
func (*CreateSpecResponse) Descriptor() ([]byte, []int) {
	return file_stock_spec_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSpecResponse) GetResponse() *typepb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type UpdateSpecRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Spec `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateSpecRequest) Reset() {
	*x = UpdateSpecRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_spec_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSpecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSpecRequest) ProtoMessage() {}

func (x *UpdateSpecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_spec_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSpecRequest.ProtoReflect.Descriptor instead.
func (*UpdateSpecRequest) Descriptor() ([]byte, []int) {
	return file_stock_spec_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSpecRequest) GetData() []*Spec {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateSpecResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *typepb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *UpdateSpecResponse) Reset() {
	*x = UpdateSpecResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_spec_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSpecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSpecResponse) ProtoMessage() {}

func (x *UpdateSpecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_spec_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSpecResponse.ProtoReflect.Descriptor instead.
func (*UpdateSpecResponse) Descriptor() ([]byte, []int) {
	return file_stock_spec_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSpecResponse) GetResponse() *typepb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type FindSpecRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request   *typepb.Request    `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Sku       []string           `protobuf:"bytes,2,rep,name=sku,proto3" json:"sku,omitempty"`
	Commodity []string           `protobuf:"bytes,3,rep,name=commodity,proto3" json:"commodity,omitempty"`
	Volume    *typepb.Range      `protobuf:"bytes,4,opt,name=volume,proto3" json:"volume,omitempty"`
	Weight    *typepb.Range      `protobuf:"bytes,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Label     []string           `protobuf:"bytes,6,rep,name=label,proto3" json:"label,omitempty"`
	CreatedAt *typepb.Datepicker `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *FindSpecRequest) Reset() {
	*x = FindSpecRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_spec_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindSpecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSpecRequest) ProtoMessage() {}

func (x *FindSpecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_spec_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSpecRequest.ProtoReflect.Descriptor instead.
func (*FindSpecRequest) Descriptor() ([]byte, []int) {
	return file_stock_spec_proto_rawDescGZIP(), []int{5}
}

func (x *FindSpecRequest) GetRequest() *typepb.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *FindSpecRequest) GetSku() []string {
	if x != nil {
		return x.Sku
	}
	return nil
}

func (x *FindSpecRequest) GetCommodity() []string {
	if x != nil {
		return x.Commodity
	}
	return nil
}

func (x *FindSpecRequest) GetVolume() *typepb.Range {
	if x != nil {
		return x.Volume
	}
	return nil
}

func (x *FindSpecRequest) GetWeight() *typepb.Range {
	if x != nil {
		return x.Weight
	}
	return nil
}

func (x *FindSpecRequest) GetLabel() []string {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *FindSpecRequest) GetCreatedAt() *typepb.Datepicker {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type FindSpecResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *typepb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Data     []*Spec          `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *FindSpecResponse) Reset() {
	*x = FindSpecResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_spec_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindSpecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSpecResponse) ProtoMessage() {}

func (x *FindSpecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_spec_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSpecResponse.ProtoReflect.Descriptor instead.
func (*FindSpecResponse) Descriptor() ([]byte, []int) {
	return file_stock_spec_proto_rawDescGZIP(), []int{6}
}

func (x *FindSpecResponse) GetResponse() *typepb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *FindSpecResponse) GetData() []*Spec {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_stock_spec_proto protoreflect.FileDescriptor

var file_stock_spec_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x1a, 0x11, 0x66, 0x73, 0x2f, 0x64, 0x69,
	0x72, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x11, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb4, 0x02, 0x0a, 0x04, 0x53, 0x70, 0x65, 0x63, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x6b, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x6b, 0x75,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74,
	0x79, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x77,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x2c, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x2e,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x12, 0x24, 0x0a, 0x09, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x66, 0x73, 0x2e, 0x44, 0x69, 0x72, 0x52, 0x08, 0x70,
	0x68, 0x6f, 0x74, 0x6f, 0x44, 0x69, 0x72, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x1a, 0x38, 0x0a, 0x0a, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x34, 0x0a, 0x11,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x41, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x65, 0x63,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x34, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x70, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x2e, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x41, 0x0a, 0x12, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x70, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2b, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xff,
	0x01, 0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x70, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x6b, 0x75, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x73, 0x6b, 0x75, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x69, 0x74, 0x79, 0x12, 0x24, 0x0a, 0x06,
	0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x30,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x70,
	0x69, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x22, 0x60, 0x0a, 0x10, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x70, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x42, 0x17, 0x5a, 0x15, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x2f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_stock_spec_proto_rawDescOnce sync.Once
	file_stock_spec_proto_rawDescData = file_stock_spec_proto_rawDesc
)

func file_stock_spec_proto_rawDescGZIP() []byte {
	file_stock_spec_proto_rawDescOnce.Do(func() {
		file_stock_spec_proto_rawDescData = protoimpl.X.CompressGZIP(file_stock_spec_proto_rawDescData)
	})
	return file_stock_spec_proto_rawDescData
}

var file_stock_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_stock_spec_proto_goTypes = []interface{}{
	(*Spec)(nil),                  // 0: stock.Spec
	(*CreateSpecRequest)(nil),     // 1: stock.CreateSpecRequest
	(*CreateSpecResponse)(nil),    // 2: stock.CreateSpecResponse
	(*UpdateSpecRequest)(nil),     // 3: stock.UpdateSpecRequest
	(*UpdateSpecResponse)(nil),    // 4: stock.UpdateSpecResponse
	(*FindSpecRequest)(nil),       // 5: stock.FindSpecRequest
	(*FindSpecResponse)(nil),      // 6: stock.FindSpecResponse
	nil,                           // 7: stock.Spec.LabelEntry
	(*fspb.Dir)(nil),              // 8: fs.Dir
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*typepb.Response)(nil),       // 10: types.Response
	(*typepb.Request)(nil),        // 11: types.Request
	(*typepb.Range)(nil),          // 12: types.Range
	(*typepb.Datepicker)(nil),     // 13: types.Datepicker
}
var file_stock_spec_proto_depIdxs = []int32{
	7,  // 0: stock.Spec.label:type_name -> stock.Spec.LabelEntry
	8,  // 1: stock.Spec.photo_dir:type_name -> fs.Dir
	9,  // 2: stock.Spec.created_at:type_name -> google.protobuf.Timestamp
	0,  // 3: stock.CreateSpecRequest.data:type_name -> stock.Spec
	10, // 4: stock.CreateSpecResponse.response:type_name -> types.Response
	0,  // 5: stock.UpdateSpecRequest.data:type_name -> stock.Spec
	10, // 6: stock.UpdateSpecResponse.response:type_name -> types.Response
	11, // 7: stock.FindSpecRequest.request:type_name -> types.Request
	12, // 8: stock.FindSpecRequest.volume:type_name -> types.Range
	12, // 9: stock.FindSpecRequest.weight:type_name -> types.Range
	13, // 10: stock.FindSpecRequest.created_at:type_name -> types.Datepicker
	10, // 11: stock.FindSpecResponse.response:type_name -> types.Response
	0,  // 12: stock.FindSpecResponse.data:type_name -> stock.Spec
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_stock_spec_proto_init() }
func file_stock_spec_proto_init() {
	if File_stock_spec_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stock_spec_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Spec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_spec_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSpecRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_spec_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSpecResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_spec_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSpecRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_spec_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSpecResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_spec_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindSpecRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_spec_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindSpecResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stock_spec_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stock_spec_proto_goTypes,
		DependencyIndexes: file_stock_spec_proto_depIdxs,
		MessageInfos:      file_stock_spec_proto_msgTypes,
	}.Build()
	File_stock_spec_proto = out.File
	file_stock_spec_proto_rawDesc = nil
	file_stock_spec_proto_goTypes = nil
	file_stock_spec_proto_depIdxs = nil
}
