// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: stock/storehouse.proto

package stockpb

import (
	typepb "estore/protoc/typepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Storehouse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                             // 倉庫ID
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                         // 倉庫名稱
	Phone    *typepb.Phone          `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`                       // 電話
	Address  *typepb.Address        `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`                   // 地址
	CreateAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"` // 建立時間
}

func (x *Storehouse) Reset() {
	*x = Storehouse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_storehouse_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Storehouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Storehouse) ProtoMessage() {}

func (x *Storehouse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_storehouse_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Storehouse.ProtoReflect.Descriptor instead.
func (*Storehouse) Descriptor() ([]byte, []int) {
	return file_stock_storehouse_proto_rawDescGZIP(), []int{0}
}

func (x *Storehouse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Storehouse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Storehouse) GetPhone() *typepb.Phone {
	if x != nil {
		return x.Phone
	}
	return nil
}

func (x *Storehouse) GetAddress() *typepb.Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Storehouse) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

type CreateStorehouseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Storehouse `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateStorehouseRequest) Reset() {
	*x = CreateStorehouseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_storehouse_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStorehouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStorehouseRequest) ProtoMessage() {}

func (x *CreateStorehouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_storehouse_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStorehouseRequest.ProtoReflect.Descriptor instead.
func (*CreateStorehouseRequest) Descriptor() ([]byte, []int) {
	return file_stock_storehouse_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStorehouseRequest) GetData() []*Storehouse {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateStorehouseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *typepb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *CreateStorehouseResponse) Reset() {
	*x = CreateStorehouseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_storehouse_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStorehouseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStorehouseResponse) ProtoMessage() {}

func (x *CreateStorehouseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_storehouse_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStorehouseResponse.ProtoReflect.Descriptor instead.
func (*CreateStorehouseResponse) Descriptor() ([]byte, []int) {
	return file_stock_storehouse_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStorehouseResponse) GetResponse() *typepb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type UpdateStorehouseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Storehouse `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateStorehouseRequest) Reset() {
	*x = UpdateStorehouseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_storehouse_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStorehouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStorehouseRequest) ProtoMessage() {}

func (x *UpdateStorehouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_storehouse_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStorehouseRequest.ProtoReflect.Descriptor instead.
func (*UpdateStorehouseRequest) Descriptor() ([]byte, []int) {
	return file_stock_storehouse_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateStorehouseRequest) GetData() []*Storehouse {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateStorehouseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *typepb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *UpdateStorehouseResponse) Reset() {
	*x = UpdateStorehouseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_storehouse_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStorehouseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStorehouseResponse) ProtoMessage() {}

func (x *UpdateStorehouseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_storehouse_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStorehouseResponse.ProtoReflect.Descriptor instead.
func (*UpdateStorehouseResponse) Descriptor() ([]byte, []int) {
	return file_stock_storehouse_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateStorehouseResponse) GetResponse() *typepb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type FindStorehouseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request  *typepb.Request    `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Id       []string           `protobuf:"bytes,2,rep,name=id,proto3" json:"id,omitempty"`
	LikeName string             `protobuf:"bytes,3,opt,name=like_name,json=likeName,proto3" json:"like_name,omitempty"`
	CreateAt *typepb.Datepicker `protobuf:"bytes,4,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
}

func (x *FindStorehouseRequest) Reset() {
	*x = FindStorehouseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_storehouse_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindStorehouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindStorehouseRequest) ProtoMessage() {}

func (x *FindStorehouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_storehouse_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindStorehouseRequest.ProtoReflect.Descriptor instead.
func (*FindStorehouseRequest) Descriptor() ([]byte, []int) {
	return file_stock_storehouse_proto_rawDescGZIP(), []int{5}
}

func (x *FindStorehouseRequest) GetRequest() *typepb.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *FindStorehouseRequest) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *FindStorehouseRequest) GetLikeName() string {
	if x != nil {
		return x.LikeName
	}
	return ""
}

func (x *FindStorehouseRequest) GetCreateAt() *typepb.Datepicker {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

type FindStorehouseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *typepb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Data     []*Storehouse    `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *FindStorehouseResponse) Reset() {
	*x = FindStorehouseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stock_storehouse_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindStorehouseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindStorehouseResponse) ProtoMessage() {}

func (x *FindStorehouseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_storehouse_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindStorehouseResponse.ProtoReflect.Descriptor instead.
func (*FindStorehouseResponse) Descriptor() ([]byte, []int) {
	return file_stock_storehouse_proto_rawDescGZIP(), []int{6}
}

func (x *FindStorehouseResponse) GetResponse() *typepb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *FindStorehouseResponse) GetData() []*Storehouse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_stock_storehouse_proto protoreflect.FileDescriptor

var file_stock_storehouse_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x1a,
	0x13, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb7, 0x01,
	0x0a, 0x0a, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x22, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x05, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x37,
	0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22, 0x40, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x68, 0x6f,
	0x75, 0x73, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x47, 0x0a, 0x18, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x40, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x47, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2b, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x9e, 0x01,
	0x0a, 0x15, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x69, 0x6b, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x69, 0x6b, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2e,
	0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x70, 0x69,
	0x63, 0x6b, 0x65, 0x72, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22, 0x6c,
	0x0a, 0x16, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x17, 0x5a, 0x15,
	0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stock_storehouse_proto_rawDescOnce sync.Once
	file_stock_storehouse_proto_rawDescData = file_stock_storehouse_proto_rawDesc
)

func file_stock_storehouse_proto_rawDescGZIP() []byte {
	file_stock_storehouse_proto_rawDescOnce.Do(func() {
		file_stock_storehouse_proto_rawDescData = protoimpl.X.CompressGZIP(file_stock_storehouse_proto_rawDescData)
	})
	return file_stock_storehouse_proto_rawDescData
}

var file_stock_storehouse_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_stock_storehouse_proto_goTypes = []interface{}{
	(*Storehouse)(nil),               // 0: stock.Storehouse
	(*CreateStorehouseRequest)(nil),  // 1: stock.CreateStorehouseRequest
	(*CreateStorehouseResponse)(nil), // 2: stock.CreateStorehouseResponse
	(*UpdateStorehouseRequest)(nil),  // 3: stock.UpdateStorehouseRequest
	(*UpdateStorehouseResponse)(nil), // 4: stock.UpdateStorehouseResponse
	(*FindStorehouseRequest)(nil),    // 5: stock.FindStorehouseRequest
	(*FindStorehouseResponse)(nil),   // 6: stock.FindStorehouseResponse
	(*typepb.Phone)(nil),             // 7: types.Phone
	(*typepb.Address)(nil),           // 8: types.Address
	(*timestamppb.Timestamp)(nil),    // 9: google.protobuf.Timestamp
	(*typepb.Response)(nil),          // 10: types.Response
	(*typepb.Request)(nil),           // 11: types.Request
	(*typepb.Datepicker)(nil),        // 12: types.Datepicker
}
var file_stock_storehouse_proto_depIdxs = []int32{
	7,  // 0: stock.Storehouse.phone:type_name -> types.Phone
	8,  // 1: stock.Storehouse.address:type_name -> types.Address
	9,  // 2: stock.Storehouse.create_at:type_name -> google.protobuf.Timestamp
	0,  // 3: stock.CreateStorehouseRequest.data:type_name -> stock.Storehouse
	10, // 4: stock.CreateStorehouseResponse.response:type_name -> types.Response
	0,  // 5: stock.UpdateStorehouseRequest.data:type_name -> stock.Storehouse
	10, // 6: stock.UpdateStorehouseResponse.response:type_name -> types.Response
	11, // 7: stock.FindStorehouseRequest.request:type_name -> types.Request
	12, // 8: stock.FindStorehouseRequest.create_at:type_name -> types.Datepicker
	10, // 9: stock.FindStorehouseResponse.response:type_name -> types.Response
	0,  // 10: stock.FindStorehouseResponse.data:type_name -> stock.Storehouse
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_stock_storehouse_proto_init() }
func file_stock_storehouse_proto_init() {
	if File_stock_storehouse_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stock_storehouse_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Storehouse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_storehouse_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStorehouseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_storehouse_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStorehouseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_storehouse_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStorehouseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_storehouse_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStorehouseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_storehouse_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindStorehouseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stock_storehouse_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindStorehouseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stock_storehouse_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stock_storehouse_proto_goTypes,
		DependencyIndexes: file_stock_storehouse_proto_depIdxs,
		MessageInfos:      file_stock_storehouse_proto_msgTypes,
	}.Build()
	File_stock_storehouse_proto = out.File
	file_stock_storehouse_proto_rawDesc = nil
	file_stock_storehouse_proto_goTypes = nil
	file_stock_storehouse_proto_depIdxs = nil
}
