// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: club/club.proto

package clubpb

import (
	typepb "estore/protoc/typepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Club struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // 商店編號
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                            // 商店名稱
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 建立時間
}

func (x *Club) Reset() {
	*x = Club{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Club) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Club) ProtoMessage() {}

func (x *Club) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Club.ProtoReflect.Descriptor instead.
func (*Club) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{0}
}

func (x *Club) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Club) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Club) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateClubRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Club `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateClubRequest) Reset() {
	*x = CreateClubRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateClubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClubRequest) ProtoMessage() {}

func (x *CreateClubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClubRequest.ProtoReflect.Descriptor instead.
func (*CreateClubRequest) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{1}
}

func (x *CreateClubRequest) GetData() []*Club {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateClubResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *typepb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *CreateClubResponse) Reset() {
	*x = CreateClubResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateClubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClubResponse) ProtoMessage() {}

func (x *CreateClubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClubResponse.ProtoReflect.Descriptor instead.
func (*CreateClubResponse) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{2}
}

func (x *CreateClubResponse) GetResponse() *typepb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type UpdateClubRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Club `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateClubRequest) Reset() {
	*x = UpdateClubRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateClubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClubRequest) ProtoMessage() {}

func (x *UpdateClubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClubRequest.ProtoReflect.Descriptor instead.
func (*UpdateClubRequest) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateClubRequest) GetData() []*Club {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateClubResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *typepb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *UpdateClubResponse) Reset() {
	*x = UpdateClubResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateClubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClubResponse) ProtoMessage() {}

func (x *UpdateClubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClubResponse.ProtoReflect.Descriptor instead.
func (*UpdateClubResponse) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateClubResponse) GetResponse() *typepb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type FindClubRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request   *typepb.Request    `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Id        []string           `protobuf:"bytes,2,rep,name=id,proto3" json:"id,omitempty"`
	LikeName  string             `protobuf:"bytes,3,opt,name=like_name,json=likeName,proto3" json:"like_name,omitempty"`
	CreatedAt *typepb.Datepicker `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *FindClubRequest) Reset() {
	*x = FindClubRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindClubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindClubRequest) ProtoMessage() {}

func (x *FindClubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindClubRequest.ProtoReflect.Descriptor instead.
func (*FindClubRequest) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{5}
}

func (x *FindClubRequest) GetRequest() *typepb.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *FindClubRequest) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *FindClubRequest) GetLikeName() string {
	if x != nil {
		return x.LikeName
	}
	return ""
}

func (x *FindClubRequest) GetCreatedAt() *typepb.Datepicker {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type FindClubResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *typepb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Data     []*Club          `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *FindClubResponse) Reset() {
	*x = FindClubResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_club_club_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindClubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindClubResponse) ProtoMessage() {}

func (x *FindClubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_club_club_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindClubResponse.ProtoReflect.Descriptor instead.
func (*FindClubResponse) Descriptor() ([]byte, []int) {
	return file_club_club_proto_rawDescGZIP(), []int{6}
}

func (x *FindClubResponse) GetResponse() *typepb.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *FindClubResponse) GetData() []*Club {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_club_club_proto protoreflect.FileDescriptor

var file_club_club_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6c, 0x75, 0x62, 0x2f, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x63, 0x6c, 0x75, 0x62, 0x1a, 0x13, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x65, 0x0a,
	0x04, 0x43, 0x6c, 0x75, 0x62, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x22, 0x33, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c,
	0x75, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x43,
	0x6c, 0x75, 0x62, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x41, 0x0a, 0x12, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x43, 0x6c, 0x75, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2b, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x33, 0x0a, 0x11,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x75, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x43, 0x6c, 0x75, 0x62, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x41, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x75, 0x62, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x9a, 0x01, 0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x6c, 0x75,
	0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x69, 0x6b, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x69, 0x6b, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x30, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x65,
	0x70, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x22, 0x5f, 0x0a, 0x10, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x6c, 0x75, 0x62, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x63, 0x6c, 0x75, 0x62, 0x2e, 0x43, 0x6c, 0x75, 0x62, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x42, 0x16, 0x5a, 0x14, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x2f, 0x63, 0x6c, 0x75, 0x62, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_club_club_proto_rawDescOnce sync.Once
	file_club_club_proto_rawDescData = file_club_club_proto_rawDesc
)

func file_club_club_proto_rawDescGZIP() []byte {
	file_club_club_proto_rawDescOnce.Do(func() {
		file_club_club_proto_rawDescData = protoimpl.X.CompressGZIP(file_club_club_proto_rawDescData)
	})
	return file_club_club_proto_rawDescData
}

var file_club_club_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_club_club_proto_goTypes = []interface{}{
	(*Club)(nil),                  // 0: club.Club
	(*CreateClubRequest)(nil),     // 1: club.CreateClubRequest
	(*CreateClubResponse)(nil),    // 2: club.CreateClubResponse
	(*UpdateClubRequest)(nil),     // 3: club.UpdateClubRequest
	(*UpdateClubResponse)(nil),    // 4: club.UpdateClubResponse
	(*FindClubRequest)(nil),       // 5: club.FindClubRequest
	(*FindClubResponse)(nil),      // 6: club.FindClubResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*typepb.Response)(nil),       // 8: types.Response
	(*typepb.Request)(nil),        // 9: types.Request
	(*typepb.Datepicker)(nil),     // 10: types.Datepicker
}
var file_club_club_proto_depIdxs = []int32{
	7,  // 0: club.Club.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: club.CreateClubRequest.data:type_name -> club.Club
	8,  // 2: club.CreateClubResponse.response:type_name -> types.Response
	0,  // 3: club.UpdateClubRequest.data:type_name -> club.Club
	8,  // 4: club.UpdateClubResponse.response:type_name -> types.Response
	9,  // 5: club.FindClubRequest.request:type_name -> types.Request
	10, // 6: club.FindClubRequest.created_at:type_name -> types.Datepicker
	8,  // 7: club.FindClubResponse.response:type_name -> types.Response
	0,  // 8: club.FindClubResponse.data:type_name -> club.Club
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_club_club_proto_init() }
func file_club_club_proto_init() {
	if File_club_club_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_club_club_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Club); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_club_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateClubRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_club_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateClubResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_club_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateClubRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_club_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateClubResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_club_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindClubRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_club_club_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindClubResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_club_club_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_club_club_proto_goTypes,
		DependencyIndexes: file_club_club_proto_depIdxs,
		MessageInfos:      file_club_club_proto_msgTypes,
	}.Build()
	File_club_club_proto = out.File
	file_club_club_proto_rawDesc = nil
	file_club_club_proto_goTypes = nil
	file_club_club_proto_depIdxs = nil
}
