{{- range .Values.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  selector:
    app: {{ .selector | default .name }}
  ports:
  - name: {{ .name }}-grpc
    port: {{ .grpcPort | default 9090 }}
    targetPort: {{ .grpcTargetPort | default 9090 }}
    protocol: TCP 
  - name: {{ .name }}-http
    port: {{ .httpPort | default 80 }}
    targetPort: {{ .httpTargetPort | default 80 }}
    protocol: TCP 
{{- end }}